# Generated by Django 5.2.8 on 2025-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mission_required_dlcs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityapplication',
            name='application_text',
        ),
        migrations.AlterField(
            model_name='mission',
            name='briefing_time',
            field=models.DateTimeField(blank=True, db_column='briefingTime', null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_time',
            field=models.DateTimeField(blank=True, db_column='endTime', null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='slotting_time',
            field=models.DateTimeField(blank=True, db_column='slottingTime', null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(blank=True, db_column='startTime', null=True),
        ),
    ]
