version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CONFIG_JWT_SECRET=${CONFIG_JWT_SECRET}
      - CONFIG_JWT_ISSUER=${CONFIG_JWT_ISSUER}
      - CONFIG_JWT_AUDIENCE=${CONFIG_JWT_AUDIENCE}
      - CONFIG_JWT_EXPIRESIN=${CONFIG_JWT_EXPIRESIN}
      - CONFIG_STEAM_API_SECRET=${CONFIG_STEAM_API_SECRET
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

volumes:
  postgres_data:
